# Generated by Django 4.2 on 2023-04-16 15:28

from django.db import migrations, models
import pricing_aws.aws.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_aws', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandleOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='handle_uploaded_file',
            name='docfile',
            field=models.FileField(upload_to='data', validators=[pricing_aws.aws.validators.isExcelDoc]),
        ),
    ]
